### PR TITLE
Upgrade `request` and `base64`

### PR DESCRIPTION
**Pull request by elsirion**
I didn't touch Bitcoin and Nostr deps since they may interact with more stuff where a coordinated upgrade would be preferable. At least Nostr seems a no-drama version bump.

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]

**Review by benthecarman — CHANGES_REQUESTED** [review]
Ci failing

**Comment by elsirion** [comment]
@benthecarman I think https://opreturnbot.com and https://zaps.benthecarman.com are just down and CI depends on it? It should probably spawn all the required infra for testing itself.

**Comment by benthecarman** [comment]
Oh yeah that's my bad lol

looks like it does need `cargo fmt`

**Comment by benthecarman** [comment]
do you need me to cut a release for this?

**Comment by elsirion** [comment]
Would be great! Then we can unify some fedimint dependencies :)

**Comment by benthecarman** [comment]
published :)

**Pull request merged**
