### PR TITLE
Bump `bitcoin` crate from v0.30.2 to v0.31.2

### PR DESCRIPTION
**Pull request by tvolk131**

### CODE REVIEW

**Comment by benthecarman** [comment]
looks like doctests are failing

**Comment by tnull** [comment]
Any reason not to directly bump to 0.32, which will be ecosystem standard for a while, according to the 'Nashville agreement'?

**Comment by tvolk131** [comment]
> Any reason not to directly bump to 0.32, which will be ecosystem standard for a while, according to the 'Nashville agreement'?

I wasn't aware of this agreement. Sgtm! Will update this PR.

**Comment by benthecarman** [comment]
would be nice to at least get one release of 0.31 for anyone that needs it

**Comment by tvolk131** [comment]
Sorry I took so long on this! Just fixed. Code coverage check is failing, but that appears to be due to a permissions issue that is outside of my control.

**Comment by benthecarman** [comment]
okay fixed the ci issue, will merge

**Comment by benthecarman** [comment]
0.7.0 up on crates.io for this, 0.8.0 up for rust-bitcoin 32

**Pull request merged**
